apiVersion: v1
kind: Service
metadata:
  name: {{ include "addition-model-api.fullname" . }}
  labels:
    {{- include "addition-model-api.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.container.port }}
      protocol: TCP
      name: {{ .Values.service.name }}
  selector:
    {{- include "addition-model-api.selectorLabels" . | nindent 4 }}
